# PyTorch
In this exercise, we will look at some basic functionality of PyTorch. Your are free to use other DL frameworks for your exercises and your project. However, the master solutions and code examples will be in PyTorch.

The [PyTorch documentation](https://pytorch.org/docs/stable/index.html) offers information on its functionality. A lot of the time, your specific question will also have been asked on the [PyTorch Forum](https://discuss.pytorch.org/), often with competent answers by the core developers (Google will find the relevant thread for you).

First, we have to install PyTorch. We will install the basic version for this exercise. For your project, if you want to run on a GPU, you'll have to make sure to have a PyTorch version installed that is compatible with the CUDA version of your NVIDIA drivers. PyTorch has an [installation guide](https://pytorch.org/get-started/locally/) that will help you with getting the right version.

In [ ]:
%pip install -q -U numpy
%pip install -q torch ipywidgets



Note: you may need to restart the kernel to use updated packages.


ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
catboost 1.2.7 requires numpy<2.0,>=1.16.0, but you have numpy 2.2.3 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.2.3 which is incompatible.
tensorflow-intel 2.18.0 requires numpy<2.1.0,>=1.26.0, but you have numpy 2.2.3 which is incompatible.
ydata-profiling 4.12.0 requires numpy<2.2,>=1.16.0, but you have numpy 2.2.3 which is incompatible.

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import torch

In [3]:
print("Torch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
print("CUDA version:", torch.version.cuda)
print("Number of GPUs:", torch.cuda.device_count())
print("Current device:", torch.cuda.current_device())
print("Device name:", torch.cuda.get_device_name(torch.cuda.current_device()))


Torch version: 2.5.1+cu121
CUDA available: True
CUDA version: 12.1
Number of GPUs: 1
Current device: 0
Device name: NVIDIA GeForce RTX 4080 SUPER


## Tensor operations
Most of PyTorch's operations have the same name as in NumPy. The basic object for storing data is the `torch.tensor`, the equivalent of the `np.array`. With the help of the [Tensor tutorial](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html), do the following:

- Create a `torch.tensor` with the elements `[[1, 2], [3, 4]]`
- Create a tensor of ones/zeros with the same shape and dtype
- Create a random tensor of the same shape
- Print the tensor's shape, data type and device
- Try to move it to the GPU
- For Mac users: Try to move it to [MPS](https://pytorch.org/docs/stable/notes/mps.html)
- Check out indexing/slicing operations, and how you can assign values to a slice.
- Combine tensors with `torch.cat` and `torch.stack`. What are the differences?
- Multiply tensors, element-wise and with matrix multiplication.

In [7]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

print(f"Tensor from list: \n {x_data} \n")

ones = torch.ones_like(x_data)
zeros = torch.zeros_like(x_data)

print(f"Ones Tensor: \n {ones} \n")
print(f"Zeros Tensor: \n {zeros} \n")

rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {rand} \n")

print(f"Shape of tensor: {x_data.shape}")
print(f"Data type of tensor: {x_data.dtype}")
print(f"Device tensor is stored on: {x_data.device}")

if torch.cuda.is_available():
    x_data = x_data.to('cuda')

print(f"Device tensor is stored on: {x_data.device}")

tensor = torch.ones(4, 4)
print('First row: ', tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:, 1] = 0
print(tensor)


Tensor from list: 
 tensor([[1, 2],
        [3, 4]]) 

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Zeros Tensor: 
 tensor([[0, 0],
        [0, 0]]) 

Random Tensor: 
 tensor([[0.3485, 0.9696],
        [0.7514, 0.5897]]) 

Shape of tensor: torch.Size([2, 2])
Data type of tensor: torch.int64
Device tensor is stored on: cpu
Device tensor is stored on: cuda:0
First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [8]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)
t2 = torch.stack([tensor, tensor, tensor])
print(t2)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]])


In [ ]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

z1 = tensor * tensor
z2 = tensor.mul(tensor)

#Elementwise multiplication (Tensors of same shape)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

agg = tensor.sum()
agg_item = agg.item()

print(agg, agg_item)


tensor(12.) 12.0


## Neural Network Basics
Solve the followings tasks with the help of the [Neural networks tutorial](https://pytorch.org/tutorials/beginner/blitz/neural_networks_tutorial.html).

The `nn.Module` is the basic class for layers, networks and models. All parameters of an `nn.Module` are automatically discovered by PyTorch and updated by back-propagation.

First, define a neural network (as a subclass of `nn.Module`) with two linear layers and a ReLU non-linearity in between. Make the input, output, and inner dimensions parameters of your network.

In [10]:
import torch.nn as nn

In [11]:
class NeuralNetwork(nn.Module):
    def __init__(self, input_dim, output_dim, inner_dim=10):
        super(NeuralNetwork, self).__init__()
        self.fc1 = nn.Linear(input_dim, inner_dim)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(inner_dim, output_dim)

    def forward(self, x):
        out = self.fc1(x)
        out = self.relu(out)
        out = self.fc2(out)
        return out

dim_in=40
dim_out=20

net=NeuralNetwork(dim_in, dim_out)
print(net)


NeuralNetwork(
  (fc1): Linear(in_features=40, out_features=10, bias=True)
  (relu): ReLU()
  (fc2): Linear(in_features=10, out_features=20, bias=True)
)


Move the entire network to the GPU/MPS.

In [15]:
print(f"Device before moving: {net.fc1.weight.device}")

if torch.cuda.is_available():
    net.to('cuda')

print(f"Device after moving: {next(net.parameters()).is_cuda}")

Device before moving: cuda:0
Device after moving: True


Print the parameters of your network.

In [17]:
params = list(net.parameters())
print(len(params))

for name, param in net.named_parameters():
    print(f"Layer: {name} | shape: {param.shape}")

4
Layer: fc1.weight | shape: torch.Size([10, 40])
Layer: fc1.bias | shape: torch.Size([10])
Layer: fc2.weight | shape: torch.Size([20, 10])
Layer: fc2.bias | shape: torch.Size([20])


Run a single forward-pass with a random input.

In [ ]:
batch_size = 5
x= torch.rand(batch_size, dim_in)

try:
    y = net(x)
except Exception as e:
    print(e)
if torch.cuda.is_available():
    x=x.to('cuda')
    y = net(x)
    print(y)
print(y.shape)
print(y)

Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat1 in method wrapper_CUDA_addmm)
tensor([[-0.1239,  0.0158,  0.2417,  0.1462, -0.2419,  0.1031,  0.3157,  0.0172,
         -0.1190, -0.3693,  0.1668,  0.2677,  0.3859, -0.2153, -0.1292, -0.3454,
         -0.0346, -0.1634,  0.2963,  0.1170],
        [ 0.0339, -0.0390,  0.3529,  0.1703, -0.3415, -0.0408,  0.3265,  0.0882,
         -0.0315, -0.2572,  0.1637,  0.2843,  0.3369, -0.2198, -0.0736, -0.3532,
         -0.2178, -0.0418,  0.3460,  0.1581],
        [ 0.0649, -0.0210,  0.1527,  0.1029, -0.4310, -0.0038,  0.4565,  0.0370,
         -0.0676, -0.2702,  0.2059,  0.2711,  0.5534, -0.3832, -0.1581, -0.3982,
         -0.2693, -0.0551,  0.2896,  0.1580],
        [ 0.0857, -0.0235,  0.1275,  0.1037, -0.3651,  0.0206,  0.4146,  0.0417,
         -0.1268, -0.2121,  0.1795,  0.3226,  0.4662, -0.3260, -0.1705, -0.3650,
         -0.2001, -0.0411,  0.3368,  0.1932],
 

Define a `nn.MSELoss` and a random target.

Compute the loss and run backpropagation.

Update the parameters of your network with a learning rate of 0.01.

Use the `AdamOptimizer` instead to update your parameters (see the [torch.optim documentation](https://pytorch.org/docs/stable/optim.html)).